### PR TITLE
PRC-56 - add support for topology in PARConnector

### PR DESCRIPTION
**Pull request by fviale**
now the user can specify the number of nodes and the topology in PA calls.

### CODE REVIEW

**Comment by lpellegr** [comment]
@fviale Please correct me if I am wrong but if I remember how PAM works, this last will produce a single task. Since there is a single task, does it make sense to expose the optional `nodes.number` parameter in PAM? what occurs if the user enter a number greater than 1?

**Comment by fviale** [comment]
the nodes.number don't control the number of tasks that will be executed, but the number of nodes "reserved" for a given task. I.e if nodes.number = 2, 2 ProActive Nodes will be reserved for a given task (wether Merge, Split, or standard), the task will still be executed in one single node, but the second one will be "busy" during the task execution and won't be accessible to other ProActive Tasks.

It is mainly used when a Task does multi-threading on its own.

**Comment by lpellegr** [comment]
:+1:

**Comment by fviale** [comment]
merged manually in the master

**Pull request closed without merging**
